### ISSUE TITLE
How to use with rails app

### ISSUE THREAD

**Issue by lucidtheory** [GeroldSetz/Mailinator-Domains#2]
This would be great to add to a rails app I am building. I am not sure how to go about implementing it. Right now I have a list of emails I am blocking using a regex but I am not sure how to go about it adding a shah hashed list like this.

Any tips?

**Comment by GeroldSetz** [comment]
Hi,

I have no skills in Ruby but found this one: https://stackoverflow.com/questions/34490/how-do-i-create-a-sha1-hash-in-ruby

Basically you have to compare the domain part of the email address in question and see if it exists in the hashed mailinator domain list .

An alternative is to use the api I provide here: https://www.block-disposable-email.com/cms/help-and-usage/easy-api/
