### ISSUE TITLE
data is vastly imcomplete

### ISSUE THREAD

**Issue by u007** [GeroldSetz/Mailinator-Domains#4]
missing a lot from like
https://gist.github.com/adamloving/4401361

or even google temporary emails has tons of domains not been listed here

**Comment by GeroldSetz** [comment]
Hi James,
this repo only holds domain names from mailinator.com. It is an excerpt and appetizer from [block-disposable-email.com](http://www.block-disposable-email.com) where you can get access to an api currently filled with > 20k domains from several dea services. If you want to stick on github sources you might also find [this repo with emailondeck.com domains ](https://github.com/GeroldSetz/emailondeck.com-domains)useful.
